export const S_SIZE = 576
export const M_SIZE = 768
export const L_SIZE = 992
export const XL_SIZE = 1200
export const XS = `@media only screen and (max-width: ${S_SIZE}px)`
export const S = `@media only screen and (min-width: ${S_SIZE}px)`
export const M = `@media only screen and (min-width: ${M_SIZE}px)`
export const L = `@media only screen and (min-width: ${L_SIZE}px)`
export const XL = `@media only screen and (min-width: ${XL_SIZE}px)`
